### PR TITLE
Update action checkout, cache, python

### PR DESCRIPTION
**Pull request by kostyaten**

### CODE REVIEW

**Comment by SukiCZ** [comment]
👍🏿 It would be nice to have updated versions in README too

**Comment by lucasssvaz** [comment]
pre-commit-ci/lite-action would also need to be updated as it uses node 16

**Comment by SukiCZ** [comment]
> [pre-commit-ci/lite-action](https://github.com/pre-commit-ci/lite-action) would also need to be updated as it uses node 16

PR opened pre-commit-ci/lite-action#12

**Comment by Manisiri** [comment]
@kostyaten - can i know why this PR  was closed. we have to update cache version to resolve warnings for precommit action .
Do you have any other PR is in progress?

**Pull request closed without merging**
