### PR TITLE
Allow action user to use custom commit message

### PR DESCRIPTION
**Pull request by aaronmak**
In my case, I might need to include a prefix or I might want a different commit message than the default. And my guess is that others might find that useful as well.

### CODE REVIEW

**Comment by asottile** [comment]
hmmm I think I'd rather not make this an option such that it can be kept uniform / searchable -- I'm open to improving the current commit message though (I think it is much too terse)

**Comment by aaronmak** [comment]
how about a prefix then? I'm trying to use it for work but it requires some sort of prefix for JIRA tickets

**Comment by estahn** [comment]
> ...that it can be kept uniform / searchable

@asottile Can you expand on your reasoning behind this? In our case, we're squashing the PR anyways hence it would just follow in line with the commit format (conventional commits) we have chosen.

There is always `git commit --amend -m "an updated commit message"` I suppose ;)

**Comment by henryiii** [comment]
This is now implemented in pre-commit.ci https://pre-commit.ci/#configuration-autoupdate_commit_msg :)

**Pull request closed without merging**
